name: HelmChartList
on:
  push:
    branches: ['main']

jobs:
  deployment-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Helm Chart List
        id: setup-list-matrix
        run: |
          MATRIX_PARAMS_COMBINATIONS=''
          cd ./helm_charts
          for d in * ; do
              MATRIX_PARAMS_COMBINATIONS+="{\"name\": \"${d}\" },"
          done
          echo $MATRIX_PARAMS_COMBINATIONS
          echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      matrix-combinations: ${{ steps.setup-list-matrix.outputs.matrix-combinations }}

  helm-deployment:
    runs-on: ubuntu-latest
    needs: deployment-setup
    strategy:
      matrix: ${{ fromJson(needs.deployment-setup.outputs.matrix-combinations) }}
    steps:
      - run: |
          echo foo=${{ matrix.name }}
  
